#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-metrics-reporter-config
Version  : 3.0.0
Release  : 1
URL      : http://repo1.maven.org/maven2/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.jar
Source0  : http://repo1.maven.org/maven2/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.jar
Source1  : http://repo1.maven.org/maven2/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-metrics-reporter-config-data = %{version}-%{release}
BuildRequires : apache-maven
BuildRequires : buildreq-mvn

%description
No detailed description available

%package data
Summary: data components for the mvn-metrics-reporter-config package.
Group: Data

%description data
data components for the mvn-metrics-reporter-config package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.jar
/usr/share/java/.m2/repository/com/addthis/metrics/reporter-config3/3.0.0/reporter-config3-3.0.0.pom
